### PR TITLE
Fix get all users controller

### LINKED ISSUE #87: Fix getAllUsers controller
It does not support getting all users (or even a single one), which is the main thing it should do.

If you look at the code:
https://github.com/JuhoBjn/online-store/blob/ac40b8300d31edbbf46d890418933173faf04607/backend/controllers/users.js#L38-L56

you can see that it's not handling the array that is coming from the model correctly so response in always 200 OK and an empty JSON object.

Easy way to fix is just limit what the SQL query returns (SELECT specific fields) and return that array via the API.

* [ ] fix controller
* [ ] add better test
* [ ] check that it actually works

### PR DESCRIPTION
**Pull request by JuhoBjn**
Fix the backend endpoint for getting all users. Updated the test case for it to check the formatting and user object fields of the returned array.

Closes #87

### CODE REVIEW

File: backend/controllers/users.js [hunk 1]
```diff
@@ -181,20 +181,9 @@ const getUser = async (req, res) => {
...
-      first_name: response.first_name,
-      last_name: response.last_name,
-      email: response.email,
-      postal_code: response.postal_code,
-      city: response.city,
-      country: response.country,
-      phone: response.phone,
-      premium: response.premium
-    });
+    res.json(response);
```
Comment (vaasuu) [inline backend/controllers/users.js:186]: I'd add a return and explicit status code here to avoid possible problems and make things clear
```suggestion
    return res.status(200).json(response);
```

File: backend/models/users.js [hunk 2]
```diff
@@ -6,7 +6,10 @@ const users = {
    * @returns all users
    */
   findAll: async () => {
-    const queryString = `SELECT * FROM users`;
+    const queryString = `
+      SELECT id, first_name AS firstname, last_name AS lastname, email,
+      postal_code AS postalcode, city, country, phone, premium
+      FROM users`;
     const [rows] = await promisePool.query(queryString);
     return rows === undefined ? null : rows;
```
Comment (vaasuu) [inline backend/models/users.js:14]: This returns an array (which is never undefined) so could simplify
```suggestion
    return rows;
```

File: backend/controllers/users.js [hunk 3]
```diff
@@ -181,20 +181,9 @@ const getUser = async (req, res) => {
...
   } else {
     res.status(404).json({ message: "No users found" });
   }
```
Comment (vaasuu) [inline backend/controllers/users.js:189]: That findAll always returns array (may be empty array), so just return that. Also need to catch errors.
Returning an empty array instead of 404 when the table is empty makes handling stuff easier on frontend.
```suggestion
  try {
    const response = await userModels.findAll();
    return res.status(200).json(response);
  } catch (error) {
    return res.status(500).json({ message: "Internal server error" });
  }
```

**Review by vaasuu — CHANGES_REQUESTED** [review]
I made things a bit better.

File: backend/controllers/users.js (hunk 3 above)
Comment (JuhoBjn) [reply backend/controllers/users.js]: Resolved in commit [1b3ee79](https://github.com/JuhoBjn/online-store/pull/92/commits/1b3ee791f3727433c65c88e63d32209ee2b56d20)

**Review by vaasuu — APPROVED** [review]
Looks good now
